# Generated by Django 4.0.4 on 2023-09-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_name'),
        ('products', '0002_rename_prodcut_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('orders_supplied', models.ManyToManyField(related_name='suppliers', to='orders.order')),
                ('products_supplied', models.ManyToManyField(related_name='suppliers', to='products.product')),
            ],
        ),
    ]
